version: 2

jobs:
  plan-apply:
    working_directory: /tmp/project
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    parameters:
      team:
        type: string
      environment:
        type: string
      stack:
        type: string
#    environment:
#      TF_VAR_team_name: ankit
#      TF_VAR_environment: stg
    steps:
      - checkout
      - run:
          name: terraform init & plan
          command: |
            cd week2/stacks/<< parameters.stack >>
            terraform init -input=false -backend-config="key=<< parameters.team >>/<< parameters.environment >>/<< parameters.stack >>"
            terraform plan -var-file=../../environments/<< parameter.environment >>.tfvars -out tfapply
      - persist_to_workspace:
          root: .
          paths:
            - .

  apply:
    environment:
      TF_VAR_team_name: ankit
      TF_VAR_environment: stg
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - attach_workspace:
          at: .
      - run:
          name: terraform
          command: |
            cd week2/stacks/networking
            terraform apply -auto-approve tfapply
      - persist_to_workspace:
          root: .
          paths:
            - .

  # plan-destroy:
  #   docker:
  #     - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
  #   steps:
  #     - attach_workspace:
  #         at: .
  #     - run:
  #         name: terraform create destroy plan
  #         command: |
  #           terraform plan -destroy -out tfdestroy -var-file terraform.tfvars
  #     - persist_to_workspace:
  #         root: .
  #         paths:
  #           - .

  # destroy:
  #   docker:
  #     - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
  #   steps:
  #     - attach_workspace:
  #         at: .
  #     - run:
  #         name: terraform destroy
  #         command: |
  #           terraform apply -auto-approve tfdestroy
workflows:
  version: 2
  networking_deploy_stg:
    jobs:
      - plan-apply:
          team: 'ankit'
          environment: 'stg'
          stack: 'networking'
      - hold-apply:
          type: approval
          requires:
            - plan-apply
      - apply:
          requires:
            - hold-apply
      # - plan-destroy:
      #     requires:
      #       - apply
      # - hold-destroy:
      #     type: approval
      #     requires:
      #       - plan-destroy
      # - destroy:
      #     requires:
      #       - hold-destroy
