version: 2.1

parameters:
  team:
    type: string
    default: 'ankit'

jobs:
  plan:
    working_directory: /tmp/project
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    parameters:
      environment:
        type: string
      stack:
        type: string
    steps:
      - checkout
      - run:
          name: terraform init & plan
          command: |
            cd week2/stacks/<< parameters.stack >>
            terraform init -input=false -backend-config="key=<< pipeline.parameters.team >>/<< parameters.environment >>/<< parameters.stack >>"
            terraform plan \
            -var 'team_name=<< pipeline.parameters.team >>' \
            -var-file=../../environments/<< parameters.stack >>/<< parameters.environment >>.tfvars \
            -out tfapply
      - persist_to_workspace:
          root: .
          paths:
            - .

  apply:
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    parameters:
      stack:
        type: string
    steps:
      - attach_workspace:
          at: .
      - run:
          name: terraform
          command: |
            cd week2/stacks/<< parameters.stack >>
            terraform apply -auto-approve tfapply
      - persist_to_workspace:
          root: .
          paths:
            - .

  # plan-destroy:
  #   docker:
  #     - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
  #   steps:
  #     - attach_workspace:
  #         at: .
  #     - run:
  #         name: terraform create destroy plan
  #         command: |
  #           terraform plan -destroy -out tfdestroy -var-file terraform.tfvars
  #     - persist_to_workspace:
  #         root: .
  #         paths:
  #           - .

  # destroy:
  #   docker:
  #     - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
  #   steps:
  #     - attach_workspace:
  #         at: .
  #     - run:
  #         name: terraform destroy
  #         command: |
  #           terraform apply -auto-approve tfdestroy
workflows:
  version: 2
  networking:
    jobs:
      - plan:
          name: networking-plan-stg
          environment: 'stg'
          stack: 'networking'
      - approve-stg:
          type: approval
          requires:
            - networking-plan-stg
      - apply:
          name: networking-apply-stg
          stack: 'networking'
          requires:
            - approve-stg
      - plan:
          name: networking-plan-prod
          environment: 'prod'
          stack: 'networking'
          requires:
            - apply-stg
      - approve-prod:
          type: approval
          requires:
            - networking-plan-prod
      - apply:
          name: apply-prod
          stack: 'networking'
          requires:
            - networking-approve-prod
  eks:
    jobs:
      - plan:
          name: eks-plan-stg
          environment: 'stg'
          stack: 'eks'
      - approve-stg:
          type: approval
          requires:
            - eks-plan-stg
      - apply:
          name: eks-apply-stg
          stack: 'eks'
          requires:
            - approve-stg
      - plan:
          name: eks-plan-prod
          environment: 'prod'
          stack: 'eks'
          requires:
            - eks-apply-stg
      - approve-prod:
          type: approval
          requires:
            - eks-plan-prod
      - apply:
          name: eks-apply-prod
          stack: 'eks'
          requires:
            - approve-prod
  app-a:
    jobs:
      - plan:
          name: app-a-plan-stg
          environment: 'stg'
          stack: 'app-a'
      - approve-stg:
          type: approval
          requires:
            - app-a-plan-stg
      - apply:
          name: app-a-apply-stg
          stack: 'app-a'
          requires:
            - approve-stg
      - plan:
          name: app-a-plan-prod
          environment: 'prod'
          stack: 'app-a'
          requires:
            - app-a-apply-stg
      - approve-prod:
          type: approval
          requires:
            - app-a-plan-prod
      - apply:
          name: app-a-apply-prod
          stack: 'app-a'
          requires:
            - app-a-approve-prod
      # - plan-destroy:
      #     requires:
      #       - apply
      # - hold-destroy:
      #     type: approval
      #     requires:
      #       - plan-destroy
      # - destroy:
      #     requires:
      #       - hold-destroy
